
name: "SignFire Controller"
description: "Located in the control case on the MindShark Sign"
solenoids: 
  - name: main_supply
    type: supply
    mode: NC
    header_pin: 7
    metadata:
      voltage: 120
  - name: sign_trench_inlet
    type: supply
    header_pin: 11
    mode: NC
    metadata:
      voltage: 120
  - name: sign_trench_outlet
    type: supply
    header_pin: 13
    mode: NC
    metadata:
      voltage: 120
  - name: sign_0
    type: outlet
    header_pin: 15
    mode: NC
    metadata:
      voltage: 120
  - name: sign_2
    type: outlet
    header_pin: 29
    mode: NC
    metadata:
      voltage: 120
  - name: sign_3
    type: outlet
    header_pin: 31
    mode: NC
    metadata:
      voltage: 120
  - name: sign_4
    type: outlet
    header_pin: 33
    mode: NC
    metadata:
      voltage: 120
igniters:
  - name: pillar_crown_0
    type: glowfly
    header_pin: 22
    metadata:
      description: 'Left Pillar Pilot Crown'
  - name: pillar_crown_1
    type: glowfly
    header_pin: 40
    metadata:
      description: 'Right Pillar Pilot Crown'
  - name: sign_pilot_0
    type: glowfly
    header_pin: 35
    metadata:
      description: 'Left side pilot lighter'
  - name: sign_pilot_1
    type: glowfly
    header_pin: 38
    metadata:
      description: 'Right side pilot lighter'